### ISSUE TITLE
bravado: Regression between between 8.0.1 and 8.1.0: Response has no attribute `headers`

### ISSUE THREAD

**Issue by asottile** [Yelp/bravado#206]
```python
Traceback (most recent call last):

## ...

  File "/nail/home/asottile/trees/www_pages/virtualenv_run/lib/python2.7/site-packages/bravado/client.py", line 111, in from_url
    spec_dict = loader.load_spec(spec_url)
  File "/nail/home/asottile/trees/www_pages/virtualenv_run/lib/python2.7/site-packages/bravado/swagger_model.py", line 101, in load_spec
    content_type = response.headers.get('content-type', '').lower()
AttributeError: 'Response' object has no attribute 'headers'
```

CC @sjaensch

**Comment by analogue** [comment]
FYI,  the headers property is missing from TwistedClient in bravado_promised. Fixing internally.

**Comment by striglia** [comment]
Same core issue as https://github.com/striglia/pyramid_swagger/pull/159? Can you link the bravado-core issue here?
