### ISSUE TITLE
SwaggerMappingError when trying to load spec with root path.

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#239]
I'm trying to write a spec that will perform a POST on a url like "domain.com/", note that the url is at the root.

In the online Swagger Editor, this schema correctly validates and performs a POST, but when using bravado, I'm unable to load the schema json.

I get "bravado_core.exception.SwaggerMappingError: Could not extract resource name from path /"

Here is an example part of my 2.0 spec:
...
```
    "host": "example.com",
    "schemes": [
        "https"
    ],
    "basePath": "/",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/": {
            "post": {
```
...

In the online swagger editor, this will correctly POST to "https://example.com/", but I get an error trying to load the spec in bravado. My code is on:
bravado==7.0.0
bravado-core==4.0.0

**Comment by bxm156** [comment]
So I discovered I have to add a "tag" and "operationId", then reference it by client.<tag>.<operationId>.

pretty confusing, not sure if thats documented anywhere.

**Comment by striglia** [comment]
Can you post your full traceback and precisely what line of code produces it? I think this isn't the first time working with semi-complete specs caused a low-level error....shouldn't spec validation be catching this?

**Comment by bxm156** [comment]
```
Traceback (most recent call last):
  File "test_forward.py", line 4, in <module>
    'file://localhost/nail/home/bmarty/services/scrubbed/forwarding.json'
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/client.py", line 110, in from_url
    return cls.from_spec(spec_dict, spec_url, http_client, config)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/client.py", line 129, in from_spec
    spec_dict, origin_url, http_client, config)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado_core/spec.py", line 104, in from_dict
    spec.build()
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado_core/spec.py", line 127, in build
    self.resources = build_resources(self)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado_core/resource.py", line 67, in build_resources
    tags.append(convert_path_to_resource(path_name))
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado_core/resource.py", line 31, in convert_path_to_resource
    raise SwaggerMappingError(err_msg.format(path_name))
bravado_core.exception.SwaggerMappingError: Could not extract resource name from path /
```

**Comment by macisamuele** [comment]
Reading the specs I haven't found any constraint about the presence of the ``tag`` and ``operationId`` into the operation object. I have checked the [minimal specs](http://editor.swagger.io/spec-files/minimal.yaml) and there is no information about ``tag`` and ``operationId``.
The issue seems caused by [bravado-core](https://github.com/Yelp/bravado-core/blob/2bcb9e1d452931e683b0c3ff7c30a9bd2ae06fa2/bravado_core/resource.py#L29) which assumes that the path will match the following regex ``/.+``.
I'm going to open an issue in the [``bravado-core``](https://github.com/Yelp/bravado-core) project.
Thanks!
