### ISSUE TITLE
Bravado client hangs a lot on HTTPS connections on _lib.SSL_read

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#242]
When trying to use the Bravado  client to make a POST over HTTPS. I find my request hangs about 70% of the time. I get tired, and I interrupt it to see where its hanging at.

It looks like its hanging at some SSL read function.

CURL is working fine.

```
File "test_forward.py", line 53, in <module>
  result =  client.forwarding_service.forward_scrubbed(body=body).result()
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/http_future.py", line 70, in result
  inner_response = self.future.result(timeout=timeout)
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/requests_client.py", line 271, in result
  timeout=self.build_timeout(timeout))
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
  r = adapter.send(request, **kwargs)
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
  timeout=timeout
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  body=body, headers=headers)
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
  httplib_response = conn.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
  response.begin()
File "/usr/lib/python2.7/httplib.py", line 416, in begin
  version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 372, in _read_status
  line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 476, in readline
  data = self._sock.recv(self._rbufsize)
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 188, in recv
  data = self.connection.recv(*args, **kwargs)
File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1319, in recv
  result = _lib.SSL_read(self._ssl, buf, bufsiz)
KeyboardInterrupt
```

**Comment by bxm156** [comment]
Eventually, if I don't keyboard interrupt. I get:

```
Traceback (most recent call last):
  File "test_forward.py", line 63, in <module>
    body=body,
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/http_future.py", line 70, in result
    inner_response = self.future.result(timeout=timeout)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/requests_client.py", line 271, in result
    timeout=self.build_timeout(timeout))
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by pyang30** [comment]
I got the same problem.

**Comment by sjaensch** [comment]
Could this be kennethreitz/requests#2312? Upgrading Python resolved the issue. If you can't do that maybe try using the fido client and see if that works...?

It's not an issue with bravado though so I'm going to close this issue.
