### ISSUE TITLE
FidoClient errors when trying to pass in _request_options.

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#243]
I tried to switch from bravado.requests.HTTPClient, to the FidoClient.
Since the FidoClient doesn't provide a nice set_basic_auth function. I wrote up the header myself, and put it into a dictionary like:

```
_request_options = {
    'headers': {
        "Authorization": "Basic %s" % base64.b64encode(
            "%s:%s" % (
                "user",
                "pass"
            ),
        ),
    }
}
```

And then I fed that to Bravado via _request_options instead of using the .set_basic_auth on the HTTPClient. My call worked as expected. Then I switched it to using FidoClient, and passing in _request_options, and I get the following traceback:

```
Using virtualenv setup in /nail/home/bmarty/pg/scrubbed/virtualenv_run
Traceback (most recent call last):
  File "test_forward.py", line 63, in <module>
    _request_options=_request_options,
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/client.py", line 264, in __call__
    also_return_response=also_return_response)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/fido_client.py", line 69, in request
    request_for_twisted = self.prepare_request_for_twisted(request_params)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/fido_client.py", line 106, in prepare_request_for_twisted
    method=request_params.get('method')
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_hooks(hooks)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/requests/models.py", line 517, in prepare_hooks
    for event in hooks:
TypeError: 'NoneType' object is not iterable
```

**Comment by lucagiovagnoli** [comment]
Hi bxm156, Can you please provide some more info on how to reproduce this? 
We've been using FidoClient for months now and I've never seen this traceback

**Comment by lcofre** [comment]
@bxm156 At least in my case, I forgot to append the .result() to the call of my api.

```
pet = client.pet.getPetById(petId=42).result()
```
