### ISSUE TITLE
AttributeError: 'Future' object has no attribute 'wait'

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#244]
When using requests==2.11.0 ( the latest version) with the FidoClient, I get

```
Traceback (most recent call last):
  File "test_forward.py", line 66, in <module>
    _request_options=_request_options,
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/http_future.py", line 70, in result
    inner_response = self.future.result(timeout=timeout)
  File "/nail/home/bmarty/pg/scrubbed/virtualenv_run/local/lib/python2.7/site-packages/bravado/fido_client.py", line 145, in result
    return self._eventual_result.wait(timeout=timeout)
AttributeError: 'Future' object has no attribute 'wait'
```

**Comment by macisamuele** [comment]
Hi @bxm156 ... I have checked your issue ...
The logs are [here](https://gist.github.com/macisamuele/7682c8c8f0f82bc3541742159ee4a817).

Are you still able to reproduce the issue? If so could you give me more context? If not could you close the comment?

**Comment by bxm156** [comment]
@macisamuele I updated the requirement versions for all my packages in requirements.txt, and it started working. I tried to figure out which bump was the cause, but after spending 20 minutes on that, I gave up and figured it wasn't worth it.
