### ISSUE TITLE
Bravado can't deal with self-signed certs or certs not in default store

### ISSUE THREAD

**Issue by kenrestivo-stem** [Yelp/bravado#278]
```
>>> client = SwaggerClient.from_url('https://somewhere/api/swagger.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bravado/client.py", line 111, in from_url
    spec_dict = loader.load_spec(spec_url)
  File "/usr/local/lib/python2.7/dist-packages/bravado/swagger_model.py", line 98, in load_spec
    self.request_headers,
  File "/usr/local/lib/python2.7/dist-packages/bravado/http_future.py", line 70, in result
    inner_response = self.future.result(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/bravado/requests_client.py", line 271, in result
    timeout=self.build_timeout(timeout))
  File "/home/krestivo/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/krestivo/.local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

**Comment by macisamuele** [comment]
Hello @kenrestivo-stem the reported issue is caused by ``requests`` library.
The ``requests`` needs to set ``verify=False`` to skip SSL verification ([doc](http://docs.python-requests.org/en/master/api/#requests.adapters.BaseAdapter.send)).

Bravado doesn't support this ([``requests_client.py``](https://github.com/Yelp/bravado/blob/master/bravado/requests_client.py#L276)) because is not "production safe".

For testing I would suggest you to add your self signed certificate in the list of trusted certificates using [``REQUESTS_CA_BUNDLE``](http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification) environment variable.

If it solves your issue please close the issue, otherwise we'll be happy to support you.

**Comment by kenrestivo-stem** [comment]
Didn't have any luck with REQUESTS_CA_BUNDLE, but decided to use a proper wildcard cert and solved the problem that way.

Closing.

**Comment by jianlwu** [comment]
i hit the same issue and looking for the solution, anywhere we can override the verify=False?

**Comment by lcofre** [comment]
Hi @macisamuele 

Thanks for your explanation about `REQUESTS_CA_BUNDLE`
Sadly I couldn't make it work for bravado.

For the requests library I do the following:
```
$ export REQUESTS_CA_BUNDLE='/path/to/the/cert.pem'
$ python3
>>> import requests
>>> requests.get('https://the-site.com')
<Response [200]>
```
I load the spec from the site so I added a print of the environment variable
```
spec_url = 'https://the-site/api/swaggerapi.yaml'
http_client = RequestsClient()
loader = Loader(http_client)
print(os.environ['REQUESTS_CA_BUNDLE'])
spec_dict = loader.load_spec(spec_url)
```
And the environment var is printed correctly but load_spec() get an exception that ends with:
```
            if isinstance(e.reason, _SSLError):
                # This branch is for urllib3 v1.22 and later.
>               raise SSLError(e, request=request)
E               bravado.http_future.RequestsFutureAdapterConnectionError

[...]/lib/python3.6/site-packages/requests/adapters.py:511: RequestsFutureAdapterConnectionError
```

Thank you very much in advance for your help.

**Comment by sjaensch** [comment]
I'm going to reopen this issue and start working on it since it pops up from time to time; we should add a possibility to set SSL verification for the HTTP client.

**Comment by PascalVA** [comment]
Hey @sjaensch,

I did not get around to making a PR since I've been very busy on other projects and did not easily get the test setup up and  running. When you finish, you can also close this issue:
https://github.com/Yelp/bravado/issues/311
