### ISSUE TITLE
umsgpack is not a dependency

### ISSUE THREAD

**Issue by jessemyers** [Yelp/bravado#339]
Nonetheless, it is imported in `bravado/http_future.py`

```
>>> import bravado.http_future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jessemyers/code/opensource/bravado/bravado/http_future.py", line 6, in <module>
    import umsgpack
ModuleNotFoundError: No module named 'umsgpack'
```

This is breaking.

**Comment by jessemyers** [comment]
Supeceded by #341
